---
title: "Machine/Statistical Learning"
author: "Nduka Boika"
format: html
date: "2025-01-01"
categories: [Readings and Tutorial]
---

**Resources:** [online resources using R](https://www.statlearning.com/resources-second-edition)

[online resources using python](https://www.statlearning.com/resources-python)

[deep learning](https://dmol.pub/)

Applied

# Lesson 1

## Some concepts in machine Learning

### Big Data- What is it?

Data is data (that is, information about about a phenomenon, person or an event). When the data is voluminous(consists of many samples), has a high collection rate, is obtained from various sources etc. we can refer to this type of data as "big data". In the field of education and psychology, big data is not a new concept. example of such data are data collected and compiled by government educational agencies (e.g., NCES, PISA).

### Statistics

After collecting these data, we need to make sense of it using statistics. Statistics is an umbrella term used to desribe the process of collecting, collating/organizing, analyzing, and interpreting data as well as drawing conclusion to make decision about the data. Statistics also include data visualization. In the field of education and psychology, we analyze educational and psychological data, where for instance, we try to find the relationship stress and students' academic performance in mathematics. Applying statistics to analyze educational data falls under the branch of applied statistics called `Educational statistics`.

::: callout-note
The mechanics of applied statistics and data-analytics are the same as far as i'm concerned.
:::

### Data Science

This is simply the application of scientific principles to learn from data. Pyrcz (2024) calls it the fourth paradigms for scientific discovery or data-driven scientific discovery.

```{mermaid}
flowchart LR
  Ist_paradigmn --> experiments
  2nd_paradigmn --> modeling
  3rd_paradigmn --> Simulation
  4th_paradigmn --> Data-science
```

### Machine Learning (ML)

According to [Wikipedia](https://en.wikipedia.org/wiki/Machine_learning#Approaches); Machine learning (ML) is a field of study in [artificial intelligence](https://en.wikipedia.org/wiki/Artificial_intelligence) concerned with the development and study of `statistical algorithms` that can `learn from data and generalize to unseen data`, and thus perform tasks without explicit instructions.

Redefining ML in my own terms: This is simply computers helping humans to make sense of data (using statistical algorithms) by learning from the data. Whatever is learnt from the data can then be used to make generalization to much broader or larger data (that we usually don't know).

Statistical algorithm; Remember that computers helps us do calculations. As a result, they would need formulas that relates to the specific statistical methods you intend to implement to analyze your data. I think about algorithms as formulas or set of equation that the machine uses to learn how to train the model using data (usually called training data).

::: border
There is a computer that uses algorithms (depending on the statistical method) to train models using sample data (usually called training data).
:::

### Population

The aim of inferential statistics is to make inferences about the sample data that generalizes to an unknown larger data. The data is not "unknown" per sey, it's just that we cannot access the data. for instance, you may be interested to know the average math performance of white students in Texas public schools. This is usually impossible because it is difficult to access the target population (assuming you are collecting the data yourself).

### Sample

Since we cannot access the entire population, we can access a section of the population (using appropriate sampling techniques)- the section of thge population that can accessed or measured is call sample.

### Variables

Variables are the specific information about a phenomena or event or person we want to know about (or measure). The variables (or vectors) together with sample size make up the dataset. Examples of variables include; gender of a person, number of dice rolled, students score on an achievement test, amount of sales made in a year etc. There are also different types of variables; two major types are discrete (take on fixed values - usually norminal) and continuous (the values are not fixed - usually interval and ratio). Other forms of variables are; independent (predictor) and dependent (outcome or response) variables. Predictors are variables that explains the outcome variable. Outcome variables are variables that we want to know more about. Predictor and outcome variables can be discrete or continuous. In ML, the predictor is the known as the input feature, while the outcome is known as the output feature in a predictive model. The model is usually accompanied by an error term.

### Inference

Machine Learning is all about estimating models for two purposes, inference or prediction. :::{.callout-note} Inference must precede prediction, because with inference, we want to generalize from sample to a model of the population. ::: Inference is all about making meaning of the sample data, and connecting the findings to the population. We answer questions like are the math scores between male and female students different in the population. We check this assumption and answer the question using sample data. Whatever the result is, we then generalize it to the population.

### Prediction

After making inference about the (sample) data and generalizing to the population, we can the predict future samples using the model. For instance, we can predict the maths score of female and male students in future samples.

::: callout-note
the focus of prediction is to get the most accurate model estimates (parameter) of future samples.
:::
